CREATE DATABASE VOTINGMACHINE;
USE VOTINGMACHINE;


CREATE TABLE MEMBER(
	MEMBER_ID			VARCHAR(20)  PRIMARY KEY,
    PASSWD				VARCHAR(200) NOT NULL,
    MEMBER_NM			VARCHAR(10)	 NOT NULL,
    SEX					CHAR(1)		 NOT NULL,
    BIRTH_AT			CHAR(10)	 NOT NULL,
    HP					VARCHAR(13)  NOT NULL,
    SMSSTS_YN			CHAR(1)		 NOT NULL,
    EMAIL	            VARCHAR(30)  NOT NULL,
    EMAILSTS_YN			CHAR(1)      NOT NULL,
    MEMBER_POINT        BIGINT		 DEFAULT 0,
    VIP_YN				CHAR(1)      DEFAULT 'n'
);

CREATE TABLE SURVEY(
	SURVEY_ID			VARCHAR(20)	 PRIMARY KEY,
	SURVEY_NM			VARCHAR(200) NOT NULL,
    CONTENT				VARCHAR(1000),
	POST_DT				DATE         DEFAULT(CURRENT_DATE),
    DUE_DT				DATE         NOT NULL,
    GIVE_POINT          BIGINT		 DEFAULT 0,
    VIP_YN				CHAR(1)      DEFAULT 'n',
    KEYWORD				VARCHAR(20)	 NOT NULL
);